### ISSUE TITLE
User Creation Error 500

### ISSUE THREAD

**Issue by hellracer** [hotspotbilling/phpnuxbill#28]
User creation error 500 if the username is > 15 characters, please fix and make it longer like 50 characters please

**Comment by hellracer** [comment]
When i read the code whatever assigned username become the phone number so if the username is > 20 it bails out because the data can't fit with phonenumber datafield because it's size is 20

**Comment by hellracer** [comment]
there are two approach to fix this, make additional mobile data field when creating users don't just copy the username to phonenumber field the other approach would be resize the phonenumber datafield equal to the length of the username :) just my 0.2$

**Comment by ibnux** [comment]
I see

I focus to make all username to be phone number, like WhatsApp verification 

Because many of my users always forgot their username, and always create new account everytime their forgot username 

Will fix it, adding condition if sms signups disabled, it will not add to phone number

But i am on vacation, i don't bring my laptop 😁
